name: nottinghamshire_county_show
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  sliding_up_panel: ^1.0.0
  flutter:
    sdk: flutter
  flutter_map: ^0.8.2
  user_location: ^0.1.2
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: "^0.2.7"
  carousel_pro: ^1.0.0
  feedback: 0.2.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/logo.jpg
   - assets/images/ntu.png
   - assets/images/title.png
   - assets/images/flags.png
   - assets/images/splash-bottom.png
   - assets/images/map.png
   - assets/images/menu-header.jpg
   - assets/images/blank-map.png
   - assets/images/NCS1.jpg
   - assets/images/NCS2.jpg
   - assets/images/NCS3.jpg
   - assets/images/NCS4.jpg
   - assets/images/NCS5.jpg
   - assets/images/NCS6.jpg
   - assets/images/NCS7.jpg
   - assets/images/NCS8.jpg
   - assets/images/NCS9.jpg
   - assets/images/NCS10.jpg
   - assets/images/Cowshowing.jpg
   - assets/images/GiantTurtles.jpg
   - assets/images/MountedGames.jpg
   - assets/images/Sheep.jpg
   - assets/images/Military.jpg
   - assets/images/NottPoliceband.jpg
   - assets/images/WorkingHunter.jpg
   



module:
    androidX: true
